AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TemplateFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: "./release/app.zip"
      FunctionName: "TemplateFunction"
      Handler: "index.handler"
      Runtime: "nodejs12.x"
      Role: "arn:aws:iam::xxxxxxxxxxxxxx:role/lambda"
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TZ: "Asia/Tokyo"
  DevVersionAlias:
    Type: "AWS::Lambda::Alias"
    Properties:
      FunctionName:
        Ref: "TemplateFunction"
      FunctionVersion: "$LATEST"
      Name: "dev"
  ProdVersionAlias:
    Type: "AWS::Lambda::Alias"
    Properties:
      FunctionName:
        Ref: "TemplateFunction"
      FunctionVersion:
        "Fn::GetAtt":
          - "RYYYYMMDD"
          - "Version"
      Name: "prod"
  RYYYYMMDD:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName:
        Ref: "TemplateFunction"
